### ISSUE TITLE
Transfer this repo and builds to an active maintainer?

### ISSUE THREAD

**Issue by huggsboson** [huggsboson/json-schema-validator#228]
I have 4 pull requests up out of a total of 17 open.  Any chance you can transfer this repo and give me access to publish builds to mavencentral so I can merge these and other patchsets?

**Comment by huggsboson** [comment]
@daveclayton

**Comment by daveclayton** [comment]
HI - would you like to take ownership of the repos?

**Comment by huggsboson** [comment]
Sure.  That would be:
json-schema-validator
json-schema-core
json-patch

?

Also are you able to publish artifacts under:
com.github.fge.json-schema-validator
com.github.fge.json-schema-core
com.github.fge.json-patch
?

If so being able to do that would be helpful as well.

**Comment by daveclayton** [comment]
Sure - I'll transfer them for you w

**Comment by huggsboson** [comment]
thanks.  Also thanks for trying to keep the project alive.

**Comment by huggsboson** [comment]
RE: com.github.fge packages were you able to publish there?

**Comment by huggsboson** [comment]
My email is jhuffaker at box dot com.  If you want to transfer the ability to publish to com.github.fge

**Comment by daveclayton** [comment]
No worries - good luck.

R/E the packages - no, I wasn't - you may want to get in touch with fge directly.
