### ISSUE TITLE
Documentation not available

### ISSUE THREAD

**Issue by Ziticca** [huggsboson/json-schema-validator#229]
Documentation located [here](http://daveclayton.github.io/json-schema-validator/2.2.x/index.html) (daveclayton.github.io) is no longer available.

Is this somehow related to the ownership transfer mentioned in #228 ?

**Comment by huggsboson** [comment]
Yeah apparently it has moved to:
http://huggsboson.github.io/json-schema-validator/2.2.x/index.html

I think I'm going to work on creating an org and moving these under that so various link breaking stops happening and we can transfer ownership as needed.

**Comment by huggsboson** [comment]
Updated README.
